In [74]:
from nba_api.stats.static import players

# using static to search for players to get player_id
nba_players = players.get_active_players()

print('Number of players fetched: {}'.format(len(nba_players)))
nba_players[:5]

Number of players fetched: 519

[{'id': 203500,
  'full_name': 'Steven Adams',
  'first_name': 'Steven',
  'last_name': 'Adams',
  'is_active': True},
 {'id': 1628389,
  'full_name': 'Bam Adebayo',
  'first_name': 'Bam',
  'last_name': 'Adebayo',
  'is_active': True},
 {'id': 200746,
  'full_name': 'LaMarcus Aldridge',
  'first_name': 'LaMarcus',
  'last_name': 'Aldridge',
  'is_active': True},
 {'id': 1629734,
  'full_name': 'Kyle Alexander',
  'first_name': 'Kyle',
  'last_name': 'Alexander',
  'is_active': True},
 {'id': 1629638,
  'full_name': 'Nickeil Alexander-Walker',
  'first_name': 'Nickeil',
  'last_name': 'Alexander-Walker',
  'is_active': True}]

In [75]:
bam = [player for player in nba_players
      if player ['full_name'] == 'Bam Adebayo'][0]
bam.values()

dict_values([1628389, 'Bam Adebayo', 'Bam', 'Adebayo', True])

In [76]:
from nba_api.stats.endpoints import playergamelog

gl = playergamelog.PlayerGameLog(player_id = '1628389')
gl = gl.get_data_frames()[0]

In [77]:


def get_playerID(Fname, Lname):
    x = [player for player in nba_players
        if player['first_name'] == f'{Fname}' and player['last_name'] == f'{Lname}'][0]
    return x['id']

get_playerID('Bam', 'Adebayo')

1628389

In [78]:
x = [player for player in nba_players
    if player['full_name'] == 'Bam Adebayo'][0]
x

{'id': 1628389,
 'full_name': 'Bam Adebayo',
 'first_name': 'Bam',
 'last_name': 'Adebayo',
 'is_active': True}

In [79]:
def get_playergl(Lname, Fname):
    x = [player for player in nba_players
        if player['first_name'] == f'{Fname}' and player['last_name'] == f'{Lname}'][0]
    ID = x['id']
    gl = playergamelog.PlayerGameLog(player_id = ID)
    gl = gl.get_data_frames()[0]
    return gl

get_playergl('Adebayo', 'Bam')

,SEASON_ID,Player_ID,Game_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,...,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,22020,1628389,0022000392,"FEB 11, 2021",MIA @ HOU,W,34,3,8,0.375,...,12,13,8,2,0,8,6,10,3,1
1,22020,1628389,0022000376,"FEB 09, 2021",MIA vs. NYK,W,35,3,9,0.333,...,2,6,2,2,2,3,0,19,-5,1
2,22020,1628389,0022000364,"FEB 07, 2021",MIA @ NYK,W,39,10,17,0.588,...,9,11,5,1,1,1,0,24,10,1
3,22020,1628389,0022000347,"FEB 05, 2021",MIA vs. WAS,W,28,5,10,0.500,...,3,4,3,1,2,0,2,21,29,1
4,22020,1628389,0022000331,"FEB 03, 2021",MIA vs. WAS,L,35,8,15,0.533,...,9,11,6,2,1,3,5,17,2,1
5,22020,1628389,0022000314,"FEB 01, 2021",MIA vs. CHA,L,39,10,15,0.667,...,6,9,2,0,3,1,6,23,-2,1
6,22020,1628389,0022000301,"JAN 30, 2021",MIA vs. SAC,W,36,7,11,0.636,...,11,13,4,2,1,5,2,18,-1,1
7,22020,1628389,0022000285,"JAN 28, 2021",MIA vs. LAC,L,35,6,16,0.375,...,10,13,7,1,0,1,1,16,-3,1
8,22020,1628389,0022000275,"JAN 27, 2021",MIA vs. DEN,L,34,6,13,0.462,...,5,7,6,0,0,3,0,15,-23,1
9,22020,1628389,0022000260,"JAN 25, 2021",MIA @ BKN,L,35,10,19,0.526,...,7,10,5,0,1,3,1,26,-3,1
10,22020,1628389,0022000244,"JAN 23, 2021",MIA @ BKN,L,38,14,20,0.700,...,5,5,9,1,0,1,5,41,4,1
11,22020,1628389,0022000234,"JAN 22, 2021",MIA @ TOR,L,34,6,13,0.462,...,5,8,4,0,0,4,2,14,1,1
12,22020,1628389,0022000220,"JAN 20, 2021",MIA @ TOR,W,34,6,14,0.429,...,8,13,7,0,0,2,1,14,2,1
13,22020,1628389,0022000206,"JAN 18, 2021",MIA vs. DET,W,35,9,15,0.600,...,9,11,5,2,1,7,5,28,5,1
14,22020,1628389,0022000192,"JAN 16, 2021",MIA vs. DET,L,34,8,11,0.727,...,6,7,6,0,3,2,2,28,-13,1
15,22020,1628389,0022000136,"JAN 09, 2021",MIA @ WAS,W,21,2,4,0.500,...,15,16,4,0,1,4,5,9,4,1
16,22020,1628389,0022000111,"JAN 06, 2021",MIA vs. BOS,L,34,5,10,0.500,...,7,8,10,0,2,2,2,15,-9,1
17,22020,1628389,0022000096,"JAN 04, 2021",MIA vs. OKC,W,28,9,10,0.900,...,7,8,4,0,0,1,2,20,25,1
18,22020,1628389,0022000071,"JAN 01, 2021",MIA @ DAL,L,36,8,12,0.667,...,9,11,2,4,0,3,3,19,-8,1
19,22020,1628389,0022000058,"DEC 30, 2020",MIA vs. MIL,W,35,7,13,0.538,...,7,8,10,1,2,2,1,22,11,1
20,22020,1628389,0022000051,"DEC 29, 2020",MIA vs. MIL,L,25,5,7,0.714,...,6,6,4,1,1,5,2,12,-32,1
21,22020,1628389,0022000005,"DEC 25, 2020",MIA vs. NOP,W,28,5,9,0.556,...,4,4,2,2,1,3,2,17,9,1
22,22020,1628389,0022000012,"DEC 23, 2020",MIA @ ORL,L,35,11,16,0.688,...,8,11,4,0,1,7,4,25,-12,1

In [88]:
from nba_api.stats.endpoints import fantasywidget

fantasydf = fantasywidget.FantasyWidget(todays_players = 'Y')
fantasydf = fantasydf.get_data_frames()[0]
fantasydf

,PLAYER_ID,PLAYER_NAME,PLAYER_POSITION,TEAM_ID,TEAM_ABBREVIATION,GP,MIN,FAN_DUEL_PTS,NBA_FANTASY_PTS,PTS,REB,AST,BLK,STL,TOV,FG3M,FGA,FG_PCT,FTA,FT_PCT
0,203999,Nikola Jokic,C,1610612743,DEN,24,35.9,54.3,56.5,26.9,11.3,8.6,0.63,1.63,3.5,1.4,18.3,13.952,5.5,19.271
1,1629029,Luka Doncic,F-G,1610612742,DAL,25,35.1,51.4,53.2,27.8,8.7,9.3,0.68,1.04,4.2,2.2,20.8,11.361,8.1,19.667
2,203507,Giannis Antetokounmpo,F,1610612749,MIL,24,33.1,50.5,52.7,28.1,11.1,5.5,1.21,1.00,3.6,1.1,18.3,13.567,10.2,15.644
3,2544,LeBron James,F,1610612747,LAL,26,34.7,46.3,47.9,25.5,7.9,7.9,0.50,1.08,3.7,2.7,18.9,12.719,5.7,18.577
4,203078,Bradley Beal,G,1610612764,WAS,21,35.3,46.2,48.1,32.8,5.0,4.5,0.57,1.29,3.0,2.5,24.5,9.664,8.3,18.613
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345,1629033,Theo Pinson,G-F,1610612752,NYK,7,2.4,0.5,0.5,0.3,0.1,0.0,0.00,0.00,0.0,0.0,0.9,1.000,0.0,0.000
346,1629686,Deividas Sirvydis,F-G,1610612765,DET,4,1.1,0.4,0.4,0.0,0.0,0.3,0.00,0.00,0.0,0.0,0.5,0.000,0.0,0.000
347,1629607,Jared Harper,G,1610612752,NYK,2,2.6,0.0,0.0,1.0,0.0,0.0,0.00,0.00,1.0,0.0,0.5,0.000,1.0,1.000
348,1630204,Ashton Hagans,G-F,1610612750,MIN,2,2.0,-0.5,-0.5,0.0,0.0,0.0,0.00,0.00,0.5,0.0,0.0,0.000,0.0,0.000
349,1628394,Anzejs Pasecniks,C-F,1610612764,WAS,1,6.3,-2.3,-2.3,0.0,1.0,1.0,0.00,0.00,5.0,0.0,1.0,0.000,0.0,0.000

In [89]:
fantasydf.rename(columns={"PLAYER_POSITION": "POS", "TEAM_ABBREVIATION": "TEAM", "FAN_DUEL_PTS":"FD"}, inplace=True)
fantasydf.drop(columns=['PLAYER_ID', 'TEAM_ID', 'NBA_FANTASY_PTS', 'FT_PCT'], inplace=True)

In [90]:
fantasydf = fantasydf.sort_values(by=['TEAM'])
fantasydf

,PLAYER_NAME,POS,TEAM,GP,MIN,FD,PTS,REB,AST,BLK,STL,TOV,FG3M,FGA,FG_PCT,FTA
282,Bruno Fernando,F-C,ATL,12,9.1,6.5,1.8,3.7,0.6,0.08,0.17,1.0,0.0,1.5,3.417,0.9
254,Onyeka Okongwu,F-C,ATL,7,10.5,8.7,3.0,3.0,0.3,0.86,0.29,0.6,0.0,2.6,3.833,1.1
26,Clint Capela,C,ATL,21,29.2,36.6,13.3,14.2,1.0,2.29,0.76,1.5,0.0,10.5,11.639,3.2
257,Brandon Goodwin,G,ATL,20,12.4,8.4,3.9,1.2,1.8,0.00,0.45,0.5,0.6,4.4,4.683,1.0
218,Rajon Rondo,G,ATL,14,15.3,12.0,3.4,2.3,3.9,0.07,0.64,1.4,0.6,3.9,5.137,0.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
280,Isaac Bonga,G,WAS,16,14.0,6.7,2.4,2.4,0.6,0.25,0.25,0.4,0.6,2.2,4.467,0.2
297,Cassius Winston,G,WAS,6,7.3,4.6,2.2,0.7,1.0,0.17,0.00,0.2,0.5,1.7,0.929,0.3
299,Anthony Gill,F,WAS,10,6.5,4.4,1.0,1.9,0.3,0.20,0.30,0.3,0.1,1.0,1.750,0.4
72,Thomas Bryant,C-F,WAS,10,27.1,25.2,14.3,6.1,1.5,0.80,0.40,1.1,0.9,9.1,5.955,2.4
349,Anzejs Pasecniks,C-F,WAS,1,6.3,-2.3,0.0,1.0,1.0,0.00,0.00,5.0,0.0,1.0,0.000,0.0

In [91]:
fantasydf['team_rank'] = fantasydf.groupby(['TEAM'])['FD'].rank(method='max', ascending = False).astype(int)

In [92]:
fantasydf.head(10)

,PLAYER_NAME,POS,TEAM,GP,MIN,FD,PTS,REB,AST,BLK,STL,TOV,FG3M,FGA,FG_PCT,FTA,team_rank
282,Bruno Fernando,F-C,ATL,12,9.1,6.5,1.8,3.7,0.6,0.08,0.17,1.0,0.0,1.5,3.417,0.9,14
254,Onyeka Okongwu,F-C,ATL,7,10.5,8.7,3.0,3.0,0.3,0.86,0.29,0.6,0.0,2.6,3.833,1.1,11
26,Clint Capela,C,ATL,21,29.2,36.6,13.3,14.2,1.0,2.29,0.76,1.5,0.0,10.5,11.639,3.2,2
257,Brandon Goodwin,G,ATL,20,12.4,8.4,3.9,1.2,1.8,0.00,0.45,0.5,0.6,4.4,4.683,1.0,12
218,Rajon Rondo,G,ATL,14,15.3,12.0,3.4,2.3,3.9,0.07,0.64,1.4,0.6,3.9,5.137,0.1,9
292,Nathan Knight,F-C,ATL,8,5.5,5.2,2.8,1.5,0.1,0.38,0.13,0.5,0.4,2.3,1.610,0.8,15
9,Trae Young,G,ATL,22,34.8,43.6,26.6,4.2,9.5,0.32,0.73,4.3,2.4,18.0,9.132,10.3,1
241,Solomon Hill,F,ATL,24,19.1,10.0,4.7,2.4,0.8,0.25,0.63,0.5,1.2,4.4,8.759,0.3,10
192,Danilo Gallinari,F,ATL,12,18.4,14.3,10.3,2.5,1.3,0.08,0.08,1.3,1.4,7.1,5.272,3.3,8
151,Bogdan Bogdanovic,G,ATL,9,23.7,17.5,9.9,3.8,2.1,0.11,0.44,1.2,2.3,8.7,3.250,1.0,7

In [93]:
fantasydf = fantasydf[fantasydf['team_rank'] <= 5]
fantasydf

,PLAYER_NAME,POS,TEAM,GP,MIN,FD,PTS,REB,AST,BLK,STL,TOV,FG3M,FGA,FG_PCT,FTA,team_rank
26,Clint Capela,C,ATL,21,29.2,36.6,13.3,14.2,1.0,2.29,0.76,1.5,0.0,10.5,11.639,3.2,2
9,Trae Young,G,ATL,22,34.8,43.6,26.6,4.2,9.5,0.32,0.73,4.3,2.4,18.0,9.132,10.3,1
35,John Collins,F-C,ATL,24,31.9,32.0,18.5,7.8,1.6,1.04,0.50,1.4,1.5,13.0,13.025,2.9,3
82,Kevin Huerter,G-F,ATL,24,31.7,24.1,12.7,3.8,3.6,0.17,1.17,1.2,2.4,11.0,10.401,0.9,5
48,De'Andre Hunter,F-G,ATL,18,32.1,28.5,17.2,5.4,2.2,0.50,0.94,1.4,1.7,11.7,9.382,4.1,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,Rui Hachimura,F,WAS,15,29.0,23.0,13.3,5.4,2.1,0.13,0.47,1.1,0.9,10.5,6.621,3.9,4
146,Ish Smith,G,WAS,18,21.0,17.9,5.5,3.6,4.7,0.22,0.78,1.0,0.3,6.3,6.349,0.8,5
14,Russell Westbrook,G,WAS,15,33.0,41.3,19.7,9.0,8.9,0.40,0.80,4.9,1.5,17.5,6.179,5.4,2
4,Bradley Beal,G,WAS,21,35.3,46.2,32.8,5.0,4.5,0.57,1.29,3.0,2.5,24.5,9.664,8.3,1
72,Thomas Bryant,C-F,WAS,10,27.1,25.2,14.3,6.1,1.5,0.80,0.40,1.1,0.9,9.1,5.955,2.4,3

In [94]:
fantasydf.sort_values(by = ['TEAM', 'team_rank'])

,PLAYER_NAME,POS,TEAM,GP,MIN,FD,PTS,REB,AST,BLK,STL,TOV,FG3M,FGA,FG_PCT,FTA,team_rank
9,Trae Young,G,ATL,22,34.8,43.6,26.6,4.2,9.5,0.32,0.73,4.3,2.4,18.0,9.132,10.3,1
26,Clint Capela,C,ATL,21,29.2,36.6,13.3,14.2,1.0,2.29,0.76,1.5,0.0,10.5,11.639,3.2,2
35,John Collins,F-C,ATL,24,31.9,32.0,18.5,7.8,1.6,1.04,0.50,1.4,1.5,13.0,13.025,2.9,3
48,De'Andre Hunter,F-G,ATL,18,32.1,28.5,17.2,5.4,2.2,0.50,0.94,1.4,1.7,11.7,9.382,4.1,4
82,Kevin Huerter,G-F,ATL,24,31.7,24.1,12.7,3.8,3.6,0.17,1.17,1.2,2.4,11.0,10.401,0.9,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,Bradley Beal,G,WAS,21,35.3,46.2,32.8,5.0,4.5,0.57,1.29,3.0,2.5,24.5,9.664,8.3,1
14,Russell Westbrook,G,WAS,15,33.0,41.3,19.7,9.0,8.9,0.40,0.80,4.9,1.5,17.5,6.179,5.4,2
72,Thomas Bryant,C-F,WAS,10,27.1,25.2,14.3,6.1,1.5,0.80,0.40,1.1,0.9,9.1,5.955,2.4,3
94,Rui Hachimura,F,WAS,15,29.0,23.0,13.3,5.4,2.1,0.13,0.47,1.1,0.9,10.5,6.621,3.9,4
146,Ish Smith,G,WAS,18,21.0,17.9,5.5,3.6,4.7,0.22,0.78,1.0,0.3,6.3,6.349,0.8,5

In [95]:
fantasydf.dtypes

PLAYER_NAME     object
POS             object
TEAM            object
GP               int64
MIN            float64
FD             float64
PTS            float64
REB            float64
AST            float64
BLK            float64
STL            float64
TOV            float64
FG3M           float64
FGA            float64
FG_PCT         float64
FTA            float64
team_rank        int32
dtype: object

In [96]:
fantasydf.round(1)

,PLAYER_NAME,POS,TEAM,GP,MIN,FD,PTS,REB,AST,BLK,STL,TOV,FG3M,FGA,FG_PCT,FTA,team_rank
26,Clint Capela,C,ATL,21,29.2,36.6,13.3,14.2,1.0,2.3,0.8,1.5,0.0,10.5,11.6,3.2,2
9,Trae Young,G,ATL,22,34.8,43.6,26.6,4.2,9.5,0.3,0.7,4.3,2.4,18.0,9.1,10.3,1
35,John Collins,F-C,ATL,24,31.9,32.0,18.5,7.8,1.6,1.0,0.5,1.4,1.5,13.0,13.0,2.9,3
82,Kevin Huerter,G-F,ATL,24,31.7,24.1,12.7,3.8,3.6,0.2,1.2,1.2,2.4,11.0,10.4,0.9,5
48,De'Andre Hunter,F-G,ATL,18,32.1,28.5,17.2,5.4,2.2,0.5,0.9,1.4,1.7,11.7,9.4,4.1,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,Rui Hachimura,F,WAS,15,29.0,23.0,13.3,5.4,2.1,0.1,0.5,1.1,0.9,10.5,6.6,3.9,4
146,Ish Smith,G,WAS,18,21.0,17.9,5.5,3.6,4.7,0.2,0.8,1.0,0.3,6.3,6.3,0.8,5
14,Russell Westbrook,G,WAS,15,33.0,41.3,19.7,9.0,8.9,0.4,0.8,4.9,1.5,17.5,6.2,5.4,2
4,Bradley Beal,G,WAS,21,35.3,46.2,32.8,5.0,4.5,0.6,1.3,3.0,2.5,24.5,9.7,8.3,1
72,Thomas Bryant,C-F,WAS,10,27.1,25.2,14.3,6.1,1.5,0.8,0.4,1.1,0.9,9.1,6.0,2.4,3

In [113]:
from nba_api.stats.endpoints import teamdashboardbyteamperformance
from nba_api.stats.static import teams

teams = teams.get_teams()

teams

[{'id': 1610612737,
  'full_name': 'Atlanta Hawks',
  'abbreviation': 'ATL',
  'nickname': 'Hawks',
  'city': 'Atlanta',
  'state': 'Atlanta',
  'year_founded': 1949},
 {'id': 1610612738,
  'full_name': 'Boston Celtics',
  'abbreviation': 'BOS',
  'nickname': 'Celtics',
  'city': 'Boston',
  'state': 'Massachusetts',
  'year_founded': 1946},
 {'id': 1610612739,
  'full_name': 'Cleveland Cavaliers',
  'abbreviation': 'CLE',
  'nickname': 'Cavaliers',
  'city': 'Cleveland',
  'state': 'Ohio',
  'year_founded': 1970},
 {'id': 1610612740,
  'full_name': 'New Orleans Pelicans',
  'abbreviation': 'NOP',
  'nickname': 'Pelicans',
  'city': 'New Orleans',
  'state': 'Louisiana',
  'year_founded': 2002},
 {'id': 1610612741,
  'full_name': 'Chicago Bulls',
  'abbreviation': 'CHI',
  'nickname': 'Bulls',
  'city': 'Chicago',
  'state': 'Illinois',
  'year_founded': 1966},
 {'id': 1610612742,
  'full_name': 'Dallas Mavericks',
  'abbreviation': 'DAL',
  'nickname': 'Mavericks',
  'city': 'Dallas',
  'state': 'Texas',
  'year_founded': 1980},
 {'id': 1610612743,
  'full_name': 'Denver Nuggets',
  'abbreviation': 'DEN',
  'nickname': 'Nuggets',
  'city': 'Denver',
  'state': 'Colorado',
  'year_founded': 1976},
 {'id': 1610612744,
  'full_name': 'Golden State Warriors',
  'abbreviation': 'GSW',
  'nickname': 'Warriors',
  'city': 'Golden State',
  'state': 'California',
  'year_founded': 1946},
 {'id': 1610612745,
  'full_name': 'Houston Rockets',
  'abbreviation': 'HOU',
  'nickname': 'Rockets',
  'city': 'Houston',
  'state': 'Texas',
  'year_founded': 1967},
 {'id': 1610612746,
  'full_name': 'Los Angeles Clippers',
  'abbreviation': 'LAC',
  'nickname': 'Clippers',
  'city': 'Los Angeles',
  'state': 'California',
  'year_founded': 1970},
 {'id': 1610612747,
  'full_name': 'Los Angeles Lakers',
  'abbreviation': 'LAL',
  'nickname': 'Lakers',
  'city': 'Los Angeles',
  'state': 'California',
  'year_founded': 1948},
 {'id': 1610612748,
  'full_name': 'Miami Heat',
  'abbreviation': 'MIA',
  'nickname': 'Heat',
  'city': 'Miami',
  'state': 'Florida',
  'year_founded': 1988},
 {'id': 1610612749,
  'full_name': 'Milwaukee Bucks',
  'abbreviation': 'MIL',
  'nickname': 'Bucks',
  'city': 'Milwaukee',
  'state': 'Wisconsin',
  'year_founded': 1968},
 {'id': 1610612750,
  'full_name': 'Minnesota Timberwolves',
  'abbreviation': 'MIN',
  'nickname': 'Timberwolves',
  'city': 'Minnesota',
  'state': 'Minnesota',
  'year_founded': 1989},
 {'id': 1610612751,
  'full_name': 'Brooklyn Nets',
  'abbreviation': 'BKN',
  'nickname': 'Nets',
  'city': 'Brooklyn',
  'state': 'New York',
  'year_founded': 1976},
 {'id': 1610612752,
  'full_name': 'New York Knicks',
  'abbreviation': 'NYK',
  'nickname': 'Knicks',
  'city': 'New York',
  'state': 'New York',
  'year_founded': 1946},
 {'id': 1610612753,
  'full_name': 'Orlando Magic',
  'abbreviation': 'ORL',
  'nickname': 'Magic',
  'city': 'Orlando',
  'state': 'Florida',
  'year_founded': 1989},
 {'id': 1610612754,
  'full_name': 'Indiana Pacers',
  'abbreviation': 'IND',
  'nickname': 'Pacers',
  'city': 'Indiana',
  'state': 'Indiana',
  'year_founded': 1976},
 {'id': 1610612755,
  'full_name': 'Philadelphia 76ers',
  'abbreviation': 'PHI',
  'nickname': '76ers',
  'city': 'Philadelphia',
  'state': 'Pennsylvania',
  'year_founded': 1949},
 {'id': 1610612756,
  'full_name': 'Phoenix Suns',
  'abbreviation': 'PHX',
  'nickname': 'Suns',
  'city': 'Phoenix',
  'state': 'Arizona',
  'year_founded': 1968},
 {'id': 1610612757,
  'full_name': 'Portland Trail Blazers',
  'abbreviation': 'POR',
  'nickname': 'Trail Blazers',
  'city': 'Portland',
  'state': 'Oregon',
  'year_founded': 1970},
 {'id': 1610612758,
  'full_name': 'Sacramento Kings',
  'abbreviation': 'SAC',
  'nickname': 'Kings',
  'city': 'Sacramento',
  'state': 'California',
  'year_founded': 1948},
 {'id': 1610612759,
  'full_name': 'San Antonio Spurs',
  'abbreviation': 'SAS',
  'nickname': 'Spurs',
  'city': 'San Antonio',
  'state': 'Texas',
  'year_founded': 1976},
 {'id': 1610612760,
  'full_name': 'Oklahoma City Thunder',
  'abbreviation': 'OKC',
  'nickname': 'Thunder',
  'city': 'Oklahoma City',
  'state': 'Oklahoma',
  'year_founded': 1967},
 {'id': 1610612761,
  'full_name': 'Toronto Raptors',
  'abbreviation': 'TOR',
  'nickname': 'Raptors',
  'city': 'Toronto',
  'state': 'Ontario',
  'year_founded': 1995},
 {'id': 1610612762,
  'full_name': 'Utah Jazz',
  'abbreviation': 'UTA',
  'nickname': 'Jazz',
  'city': 'Utah',
  'state': 'Utah',
  'year_founded': 1974},
 {'id': 1610612763,
  'full_name': 'Memphis Grizzlies',
  'abbreviation': 'MEM',
  'nickname': 'Grizzlies',
  'city': 'Memphis',
  'state': 'Tennessee',
  'year_founded': 1995},
 {'id': 1610612764,
  'full_name': 'Washington Wizards',
  'abbreviation': 'WAS',
  'nickname': 'Wizards',
  'city': 'Washington',
  'state': 'District of Columbia',
  'year_founded': 1961},
 {'id': 1610612765,
  'full_name': 'Detroit Pistons',
  'abbreviation': 'DET',
  'nickname': 'Pistons',
  'city': 'Detroit',
  'state': 'Michigan',
  'year_founded': 1948},
 {'id': 1610612766,
  'full_name': 'Charlotte Hornets',
  'abbreviation': 'CHA',
  'nickname': 'Hornets',
  'city': 'Charlotte',
  'state': 'North Carolina',
  'year_founded': 1988}]

In [122]:
ID = [team for team in teams
     if team['abbreviation'] == 'DEN'][0]
ID = ID['id']

gl = teamdashboardbyteamperformance.TeamDashboardByTeamPerformance(ID)
gl = gl.get_data_frames()[0]
gl

,GROUP_SET,GROUP_VALUE,GP,W,L,W_PCT,MIN,FGM,FGA,FG_PCT,...,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,CFID,CFPARAMS
0,Overall,2020-21,25,14,11,0.56,1225.0,1079,2249,0.48,...,1,1,1,1,1,1,1,1,175,2020-21